"""
Layer 3 (ML Attribution) Router

FastAPI router for Layer 3 ML-based attack attribution:
- Dashboard summary with attack targets
- Dynamic signatures
- Top attackers
- Packet ring statistics
"""

from typing import Optional, Dict, Any, List
from fastapi import APIRouter, HTTPException, Query, Body, Depends
from pydantic import BaseModel
from ..auth import UserContext, get_current_user

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from ..services.dpdk_service import get_dpdk_service, ANOMALY_LEVEL_NAMES

router = APIRouter(
    prefix="/layer3",
    tags=["Layer 3 ML"],
    dependencies=[Depends(get_current_user)],
)


# Response models
class AttackTarget(BaseModel):
    ip: str
    level: int
    level_name: str
    protocol: str
    attack_type: str
    dst_port: int
    z_score: float
    tier_agreement: int


class Layer3Summary(BaseModel):
    status: str
    total_attackers: int
    total_signatures: int
    packet_ring_fill: float
    attack_targets: List[AttackTarget]


class SignatureEntry(BaseModel):
    id: int
    name: str
    protocol: str
    pattern: str
    enabled: bool
    hits: int
    created: str


class AttackerEntry(BaseModel):
    src_ip: str
    packets: int
    bytes: int
    first_seen: str
    last_seen: str
    score: float


# Helper to get Layer3 reader
def get_layer3_reader():
    try:
        from parsers.layer3 import get_reader as _get_layer3_reader
        return _get_layer3_reader()
    except ImportError:
        return None


def get_layer3_writer():
    try:
        from parsers.layer3 import get_writer as _get_layer3_writer
        return _get_layer3_writer()
    except ImportError:
        return None


def generate_attack_signature(attack_target: Dict) -> Optional[Dict]:
    try:
        from parsers.layer3 import generate_attack_signature as _generate_attack_signature
        return _generate_attack_signature(attack_target)
    except ImportError:
        return None


@router.get("/summary")
async def get_layer3_summary():
    """Get Layer 3 dashboard summary with attack targets."""
    reader = get_layer3_reader()

    if reader is None:
        # Return mock data when Layer 3 module not available
        summary = {
            'status': 'idle',
            'total_attackers': 0,
            'total_signatures': 0,
            'packet_ring_fill': 0.0,
            'attack_targets': []
        }
    else:
        summary = reader.get_layer3_summary()
        # Add total_signatures field expected by dashboard
        # (reader returns dynamic_signatures.total, dashboard expects total_signatures)
        if 'dynamic_signatures' in summary:
            summary['total_signatures'] = summary['dynamic_signatures'].get('total', 0)

    # Add attack targets from per-IP anomaly data
    service = get_dpdk_service()
    per_ip_anomaly_data = service.get_per_ip_anomaly()

    attack_targets = []
    for ip_str, state in per_ip_anomaly_data.items():
        if state.get('anomaly_active', False):
            attack_targets.append({
                'ip': ip_str,
                'level': state.get('level', 0),
                'level_name': ANOMALY_LEVEL_NAMES.get(state.get('level', 0), 'UNKNOWN'),
                'protocol': state.get('anomaly_protocol_name', 'ALL'),
                'attack_type': state.get('attack_type_name', 'UNKNOWN'),
                'dst_port': state.get('anomaly_dst_port', 0),
                'z_score': round(state.get('max_z_score', 0.0), 2),
                'tier_agreement': state.get('tier_agreement', 0),
            })

    # Sort by severity level descending
    attack_targets.sort(key=lambda x: -x['level'])
    summary['attack_targets'] = attack_targets

    # Set status to active if any targets under attack
    if attack_targets:
        summary['status'] = 'active'

    return summary


@router.get("/signatures")
async def get_layer3_signatures():
    """Get dynamic signatures generated by Layer 3."""
    reader = get_layer3_reader()
    if reader is None:
        return {'signatures': [], 'count': 0}
    return reader.get_dynamic_signatures()


@router.get("/attackers")
async def get_layer3_attackers(limit: int = Query(50, ge=1, le=200)):
    """Get top source IPs (potential attackers) from Layer 3."""
    reader = get_layer3_reader()
    if reader is None:
        return {'attackers': [], 'count': 0}
    return reader.get_top_attackers(limit=limit)


@router.get("/packet-ring")
async def get_layer3_packet_ring():
    """Get packet ring buffer statistics."""
    reader = get_layer3_reader()
    if reader is None:
        return {
            'fill_level': 0.0,
            'total_capacity': 0,
            'packets_in_buffer': 0,
            'write_position': 0,
            'read_position': 0
        }
    return reader.get_packet_ring_stats()


@router.post("/signatures/generate")
async def generate_signatures():
    """Auto-generate dynamic signatures for current attacks."""
    writer = get_layer3_writer()
    if writer is None:
        raise HTTPException(status_code=503, detail='Layer 3 module not available')

    service = get_dpdk_service()
    per_ip_anomaly_data = service.get_per_ip_anomaly()

    generated = []

    for ip_str, state in per_ip_anomaly_data.items():
        anomaly_active = state.get('anomaly_active', False)
        level = state.get('level', 0)

        if anomaly_active and level >= 2:  # MEDIUM or higher
            attack_target = {
                'ip': ip_str,
                'protocol': state.get('anomaly_protocol_name', 'ALL'),
                'attack_type': state.get('attack_type_name', 'UNKNOWN'),
                'dst_port': state.get('anomaly_dst_port', 0),
                'level': level,
            }

            sig_def = generate_attack_signature(attack_target)
            if sig_def:
                sig_id = writer.add_signature(sig_def)
                if sig_id > 0:
                    generated.append({
                        'id': sig_id,
                        'target': ip_str,
                        'attack_type': attack_target['attack_type'],
                        'protocol': attack_target['protocol'],
                    })

    return {
        'generated': len(generated),
        'signatures': generated,
    }


class SignatureDefinition(BaseModel):
    name: str
    protocol: str
    pattern: Optional[str] = None
    src_ip: Optional[str] = None
    dst_ip: Optional[str] = None
    src_port: Optional[int] = None
    dst_port: Optional[int] = None
    action: str = 'drop'


@router.post("/signatures/add")
async def add_signature(sig: SignatureDefinition):
    """Manually add a dynamic signature."""
    writer = get_layer3_writer()
    if writer is None:
        raise HTTPException(status_code=503, detail='Layer 3 module not available')

    sig_id = writer.add_signature(sig.model_dump())

    if sig_id < 0:
        raise HTTPException(status_code=500, detail='Failed to add signature')

    return {'id': sig_id, 'status': 'created'}


@router.delete("/signatures/{sig_id}")
async def delete_signature(sig_id: int):
    """Remove a dynamic signature."""
    writer = get_layer3_writer()
    if writer is None:
        raise HTTPException(status_code=503, detail='Layer 3 module not available')

    if writer.remove_signature(sig_id):
        return {'status': 'removed', 'id': sig_id}
    else:
        raise HTTPException(status_code=404, detail=f'Signature {sig_id} not found')


@router.post("/signatures/{sig_id}/enable")
async def enable_signature(sig_id: int):
    """Enable a dynamic signature."""
    writer = get_layer3_writer()
    if writer is None:
        raise HTTPException(status_code=503, detail='Layer 3 module not available')

    if writer.set_signature_enabled(sig_id, True):
        return {'status': 'enabled', 'id': sig_id}
    else:
        raise HTTPException(status_code=404, detail=f'Signature {sig_id} not found')


@router.post("/signatures/{sig_id}/disable")
async def disable_signature(sig_id: int):
    """Disable a dynamic signature."""
    writer = get_layer3_writer()
    if writer is None:
        raise HTTPException(status_code=503, detail='Layer 3 module not available')

    if writer.set_signature_enabled(sig_id, False):
        return {'status': 'disabled', 'id': sig_id}
    else:
        raise HTTPException(status_code=404, detail=f'Signature {sig_id} not found')
