/* GENERATED by tests/unit/_gen_routed_fdr_vectors.py -- DO NOT EDIT. */
/* Reference outputs of experiment/routed_fdr/routed_detector.py. */
#ifndef ROUTED_FDR_VECTORS_H
#define ROUTED_FDR_VECTORS_H
#include <math.h>  /* NAN, HUGE_VAL */

typedef struct { double calib[16]; int n_calib; int score_is_none; double score; double p; } rf_conformal_case_t;
static const rf_conformal_case_t RF_CONFORMAL[] = {
  { {1.0, 2.0, 3.0, 4.0, 5.0}, 5, 0, 3.5, 0.5 },
  { {1.0, 2.0, 3.0, 4.0, 5.0}, 5, 0, 0.0, 0.999999999999 },
  { {1.0, 2.0, 3.0, 4.0, 5.0}, 5, 0, 99.0, 0.16666666666666666 },
  { {2.0, 2.0, 2.0, 2.0}, 4, 0, 2.0, 0.999999999999 },
  { {0.1, 0.5, 0.9, 1.3, 1.7, 2.1, 2.5}, 7, 0, 1.4, 0.5 },
  { {0.0}, 0, 0, 1.0, 1.0 },
  { {1.0, 2.0, 3.0}, 3, 1, 0.0, 1.0 },
  { {-3.0, -1.0, 0.0, 2.0, 4.0, 7.0}, 6, 0, -0.5, 0.7142857142857143 },
};
static const int RF_CONFORMAL_N = 8;

typedef struct { double p_z; double p_c; double p; } rf_acat_pair_case_t;
static const rf_acat_pair_case_t RF_ACAT_PAIR[] = {
  { 0.5, 0.5, 0.5 },
  { 0.01, 0.5, 0.019980299664053736 },
  { 0.5, 0.01, 0.019980299664053736 },
  { 0.001, 0.002, 0.0013333343081122773 },
  { 0.9, 0.9, 0.9 },
  { 1e-12, 1e-12, 1e-12 },
  { 1.0, 1.0, 0.999999999999 },
  { 0.2, 0.8, 0.5000000000000001 },
  { 0.05, 0.95, 0.49999999999999845 },
  { 0.3333333333, 0.6666666666, 0.4999999999333333 },
};
static const int RF_ACAT_PAIR_N = 10;

typedef struct { double pvals[32]; int n; double alpha; double acat_combine; int bh_reject; int bh_attr; double bh_alpha_star; int bh_alpha_star_has; int bh_alpha_star_attr; } rf_pvec_case_t;
static const rf_pvec_case_t RF_PVEC[] = {
  { {0.5, 0.5, 0.5, 0.5}, 4, 0.05, 0.5, 0, -1, 0.5, 1, 0 },
  { {0.001, 0.5, 0.5, 0.5, 0.5}, 5, 0.05, 0.009996744945049318, 1, 0, 0.005, 1, 0 },
  { {0.01, 0.02, 0.03, 0.04, 0.9, 0.95}, 6, 0.05, 0.06625323729473326, 0, -1, 0.06, 1, 0 },
  { {0.2, 0.2, 0.2, 0.2, 0.2}, 5, 0.05, 0.30813668275224393, 0, -1, 0.2, 1, 0 },
  { {1e-06, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9}, 8, 0.01, 1.600108296884173e-05, 1, 0, 8e-06, 1, 0 },
  { {0.04, 0.04, 0.04, 0.04}, 4, 0.05, 0.07877515647574596, 1, 0, 0.04, 1, 0 },
  { {0.9}, 1, 0.05, 0.8165700105881113, 0, -1, 0.9, 1, 0 },
  { {0.001}, 1, 0.05, 0.001999980261180867, 1, 0, 0.001, 1, 0 },
  { {0.42, 0.11, 0.88, 0.003, 0.27, 0.66, 0.91, 0.05, 0.31, 0.77, 0.009, 0.55, 0.49, 0.21, 0.95, 0.18, 0.62, 0.37, 0.08, 0.71, 0.0015}, 21, 0.05, 0.037328552309322416, 1, 20, 0.0315, 1, 20 },
  { {0.5, 0.01, 0.3, 0.01, 0.8}, 5, 0.05, 0.05011423770332374, 1, 1, 0.025, 1, 1 },
};
static const int RF_PVEC_N = 10;

#endif /* ROUTED_FDR_VECTORS_H */
