/**
 * @file test_routed_fdr.c
 * @brief Bit-level fidelity test: C routed-FDR math == Python reference.
 *
 * Validates that layer2/routed_fdr.{c} reproduces the section 5.8 routed detector
 * math from experiment/routed_fdr/routed_detector.py to <1e-9 (decisions
 * exact). The reference outputs are generated by
 * tests/unit/_gen_routed_fdr_vectors.py into routed_fdr_vectors.h (which
 * imports the Python source of truth), so this test compares C against the
 * actual Python implementation, not a hand-transcribed table.
 *
 * Covers:
 *   - routed_conformal_p   (split-conformal right-tail p, [1e-12,1-1e-12] clamp,
 *                           empty-buffer and None-score edge cases)
 *   - routed_acat_pair     (equal-0.5-weight Cauchy collapse, NO /len averaging)
 *   - routed_acat_combine  (mean Cauchy across channels)
 *   - routed_bh_reject     (BH step-up decision + smallest-p attribution)
 *   - routed_bh_alpha_star (alpha* = min_k m*p_(k)/k + attribution)
 */
#include <stdio.h>
#include <math.h>
#include <stddef.h>

#include "../../layer2/routed_fdr.h"
#include "routed_fdr_vectors.h"

#define TOL 1e-9

static int tests_run = 0, tests_passed = 0;
static double g_max_abs_err = 0.0;

static void note_err(double c, double ref)
{
    double e = fabs(c - ref);
    if (e > g_max_abs_err) g_max_abs_err = e;
}

#define CHECK(cond, msg) do { \
    tests_run++; \
    if (cond) { tests_passed++; } \
    else { printf("  FAIL: %s\n", msg); } \
} while (0)

#define CHECK_CLOSE(c, ref, msg) do { \
    note_err((c), (ref)); \
    tests_run++; \
    if (fabs((c) - (ref)) <= TOL) { tests_passed++; } \
    else { printf("  FAIL: %s (C=%.17g ref=%.17g |err|=%.3g)\n", \
                  msg, (double)(c), (double)(ref), fabs((c)-(ref))); } \
} while (0)

/* Build a conformal_path buffer from a fixed calibration array. */
static void build_path(struct conformal_path *p, const double *calib, int n)
{
    int cap = (n < 1) ? 1 : n;
    p->capacity = (size_t)cap;
    p->count = 0;
    p->head = 0;
    for (int i = 0; i < n; i++)
        conformal_path_observe(p, calib[i]);
}

static void test_conformal_p(void)
{
    printf("conformal_p (%d cases):\n", RF_CONFORMAL_N);
    for (int i = 0; i < RF_CONFORMAL_N; i++) {
        const rf_conformal_case_t *c = &RF_CONFORMAL[i];
        struct conformal_path p;
        build_path(&p, c->calib, c->n_calib);
        double score = c->score_is_none ? NAN : c->score;
        double got = routed_conformal_p(&p, score);
        CHECK_CLOSE(got, c->p, "conformal_p");
    }
}

static void test_acat_pair(void)
{
    printf("acat_pair (%d cases):\n", RF_ACAT_PAIR_N);
    for (int i = 0; i < RF_ACAT_PAIR_N; i++) {
        const rf_acat_pair_case_t *c = &RF_ACAT_PAIR[i];
        double got = routed_acat_pair(c->p_z, c->p_c);
        CHECK_CLOSE(got, c->p, "acat_pair");
    }
}

static void test_pvec(void)
{
    printf("pvec: acat_combine / bh_reject / bh_alpha_star (%d cases):\n", RF_PVEC_N);
    for (int i = 0; i < RF_PVEC_N; i++) {
        const rf_pvec_case_t *c = &RF_PVEC[i];

        double ac = routed_acat_combine(c->pvals, (size_t)c->n);
        CHECK_CLOSE(ac, c->acat_combine, "acat_combine");

        size_t attr = 12345;
        bool rej = routed_bh_reject(c->pvals, (size_t)c->n, c->alpha, &attr);
        CHECK(rej == (c->bh_reject != 0), "bh_reject decision");
        /* attribution: Python returns None (-1) when no reject; else smallest-p idx */
        int attr_i = (attr == (size_t)-1) ? -1 : (int)attr;
        CHECK(attr_i == c->bh_attr, "bh_reject attribution");

        size_t sattr = 54321;
        double astar = routed_bh_alpha_star(c->pvals, (size_t)c->n, &sattr);
        if (c->bh_alpha_star_has) {
            CHECK_CLOSE(astar, c->bh_alpha_star, "bh_alpha_star value");
        } else {
            CHECK(astar == HUGE_VAL, "bh_alpha_star = inf");
        }
        int sattr_i = (sattr == (size_t)-1) ? -1 : (int)sattr;
        CHECK(sattr_i == c->bh_alpha_star_attr, "bh_alpha_star attribution");
    }
}

int main(void)
{
    printf("=== routed_fdr fidelity test (C == Python, tol=%.0e) ===\n", TOL);
    test_conformal_p();
    test_acat_pair();
    test_pvec();
    printf("--------------------------------------------------------\n");
    printf("max abs error vs Python: %.3e\n", g_max_abs_err);
    printf("%d/%d checks passed\n", tests_passed, tests_run);
    if (tests_passed == tests_run) {
        printf("PASS: C routed-FDR math reproduces Python to <%.0e\n", TOL);
        return 0;
    }
    printf("FAIL\n");
    return 1;
}
